version: '3.9'

services:
  php:
    build: php
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./php/html:/var/www/html/
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - internal
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql-init:/docker-entrypoint-initdb.d
      - ./db/mysql-volume:/var/lib/mysql

networks:
  internal:
    driver: bridge
